name: CI

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      # Setup env
      - uses: "actions/setup-python@v2"
        with:
            python-version: "${{ matrix.python-version }}"

      - name: "Installs for ${{ matrix.python-version }}"
        run: |
          python --version
          pip install --upgrade pip wheel setuptools nox

      - name: "Run nox for ${{ matrix.python-version }}"
        run: "nox -s test-${{ matrix.python-version }}"

